# Generated by Django 4.1.7 on 2023-02-23 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Bank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("Image", models.URLField()),
                ("description", models.TextField(null=True)),
                ("link", models.URLField()),
                ("telephone", models.CharField(max_length=25)),
            ],
            options={"abstract": False,},
        ),
    ]
