# Generated by Django 4.1.7 on 2023-02-24 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("my_services", "0002_rename_image_bank_image_alter_bank_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hotal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("image", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                ("review", models.SmallIntegerField()),
                (
                    "cleanlinsess_review",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("service_review", models.SmallIntegerField(blank=True, null=True)),
                ("value_review", models.SmallIntegerField(blank=True, null=True)),
                ("language_spoken", models.CharField(max_length=200)),
            ],
            options={"abstract": False,},
        ),
    ]
